services:
  database:
    image: container-registry.oracle.com/database/express:latest
    restart: always
    container_name: "database"
    environment:
      ORACLE_PWD: test
    ports:
      - "1521:1521"
      - "5500:5500"
    volumes:
      - oracle-data:/opt/oracle/oradata
      - ./sql/startup:/opt/oracle/scripts/startup

volumes:
  oracle-data: